// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day03.DbFirstProject.Models;

public partial class job
{
    [Key]
    public short job_id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string job_desc { get; set; } = null!;

    public byte min_lvl { get; set; }

    public byte max_lvl { get; set; }

    [InverseProperty("job")]
    public virtual ICollection<employee> employees { get; set; } = new List<employee>();
}