// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day03.DbFirstProject.Models;

public partial class store
{
    [Key]
    [StringLength(4)]
    [Unicode(false)]
    public string stor_id { get; set; } = null!;

    [StringLength(40)]
    [Unicode(false)]
    public string? stor_name { get; set; }

    [StringLength(40)]
    [Unicode(false)]
    public string? stor_address { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? city { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string? state { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string? zip { get; set; }

    [InverseProperty("stor")]
    public virtual ICollection<sale> sales { get; set; } = new List<sale>();
}